package com.example.myapplication.database

import android.content.Context

import android.util.Log
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch


@Database(
    entities =
    [
      Categoria::class,
      Ingrediente::class,
     IngredienteRIcetta::class,
    RicettaCategorie::class,
    RicettaCompleta::class,
    RicettePreview::class
    ],
    version = 2,
    exportSchema = true
)
abstract class RicetteDataBase : RoomDatabase() {
    abstract fun dao(): DaoRicette

    companion object {
        private var INSTANCE: RicetteDataBase? = null

        fun getDataBase(context: Context,
                        scope:CoroutineScope) :RicetteDataBase {
            return INSTANCE?: synchronized(this)
            {
                val instance=Room.databaseBuilder(context.applicationContext,RicetteDataBase::class.java,
                "ricette_database")
                    .fallbackToDestructiveMigration()
                    .addCallback(RicetteDataBaseCallback(scope))
                    .build()
                INSTANCE=instance
                instance
            }


        }

        private class RicetteDataBaseCallback (private val  scope: CoroutineScope):RoomDatabase.Callback()
        {
            override fun onOpen(db: SupportSQLiteDatabase)
            {
                super.onOpen(db)
                Log.d("test","open")


                INSTANCE?.let { database->
                    Log.d("test","let")
                    scope.launch (Dispatchers.IO){


                        prepopulateDatabase(database.dao())

                    }
                }
               if(INSTANCE==null)
                Log.d("test","null")
            }
        }
        suspend fun prepopulateDatabase(dao:DaoRicette)
        { Log.d("test","prepopulate")
            if(dao.countIngredienti()==0) {
                dao.insertCategoria(Categoria("antipasto"))
                dao.insertCategoria(Categoria("primo"))
                dao.insertCategoria(Categoria("secondo"))
                dao.insertCategoria(Categoria("dolce"))
                dao.insertCategoria(Categoria("vegetariano"))
                dao.insertCategoria(Categoria("vegano"))
                dao.insertCategoria(Categoria("gluten free"))
                val li = listOf<String>(
                    "ACCIUGHE o ALICI [ENGRAULIS ENCHRASICHOL]",
                    "ACCIUGHE o ALICI SOTTO SALE",
                    "ACCIUGHE o ALICI SOTT'OLIO",
                    "ACETO",
                    "ACQUA",
                    "ACQUA TONICA",
                    "AGAR AGAR [EUCHEUMA spp], secco",
                    "AGLIO [ALLIUM SATIVUM], fresco",
                    "AGLIO, in polvere",
                    "AGNELLO [OVIS AGNUS]",
                    "AGNELLO, CARNE GRASSA",
                    "AGNELLO, CARNE MAGRA",
                    "AGNELLO, CARNE SEMIGRASSA",
                    "AGNELLO, CORATELLA",
                    "AGNELLO, COSTOLETTE",
                    "AGRETTI [LEPIDUM SATIVUM]",
                    "ALBICOCCHE (PRUNUS ARMENIACA)",
                    "ALBICOCCHE, polpa secca",
                    "ALCOOL PURO",
                    "ALLORO [LAURUS NOBILIS], secco",
                    "AMARENE [PRUNUS CERASUS]",
                    "AMARI A BASSA GRADAZIONE",
                    "AMARI AD ALTA GRADAZIONE",
                    "AMIDO",
                    "ANANAS [ANANAS SATIVUS]",
                    "ANANAS SCIROPPATA",
                    "ANATRA [ANAS BOSCHAS]",
                    "ANGUILLA DI FIUME [ANGUILLA ANGUILLA]",
                    "ANGUILLA DI MARE [ANGUILLA ANGUILLA]",
                    "ANGUILLA MARINATA",
                    "APERITIVI",
                    "ARACHIDI [ARACHIS HYPOGEA] CRUDE",
                    "ARACHIDI TOSTATE",
                    "ARACHIDI TOSTATE E SALATE",
                    "ARAGOSTA [PALINURUS ELEPHAS]",
                    "ARANCE [CITRUS AURANTIUM]",
                    "ARANCE, SCORZA",
                    "ARANCIATA IN LATTINA",
                    "ARINGA [CLUPEA HARENGUS]",
                    "ARINGA AFFUMICATA",
                    "ARINGA MARINATA",
                    "ARINGA SALATA",
                    "ASIAGO",
                    "ASPARAGI DI BOSCO [ASPARAGUS OFFICINALIS]",
                    "ASPARAGI DI CAMPO",
                    "ASPARAGI DI SERRA",
                    "ASPARAGI IN SCATOLA",
                    "ASTICE [HOMARUS VULGARIS]",
                    "AVENA [AVENA SATIVA]",
                    "AVOCADO [PERSEA GRATISSIMA]",
                    "BABA' AL RHUM",
                    "BABACO [CARICA PENTAGONA]",
                    "BACCALA' [MERLUCCIUS MERLUCCIUS], ammollato",
                    "BACCALA', secco",
                    "BANANA [MUSA SAPIENTIUM]",
                    "BARBABIETOLE ROSSE [BETA VULGARIS, CV RAPA, FORMA RUBRA]",
                    "BASILICO [OCIMUM BASILICUM], fresco",
                    "BASILICO, secco macinato",
                    "BEVANDE GASSATE DIETETICHE",
                    "BIETA [BETA VULGARIS, CV CICLA]",
                    "BIETA IN SCATOLA",
                    "BIGNE'",
                    "BIRRA CHIARA",
                    "BIRRA SCURA",
                    "BISCOTTI AL LATTE",
                    "BISCOTTI FROLLINI",
                    "BISCOTTI INTEGRALI",
                    "BISCOTTI PER L'INFANZIA",
                    "BISCOTTI 'PETIT BEURRE'",
                    "BISCOTTI RICOPERTI AL CIOCCOLATO",
                    "BISCOTTI SAVOIARDO",
                    "BISCOTTI WAFERS",
                    "BISCOTTO PER LA PRIMA COLAZIONE",
                    "BOVINO, CERVELLO",
                    "BOVINO, CUORE",
                    "BOVINO, FEGATO",
                    "BOVINO, LESSATO IN GELATINA, IN SCATOLA",
                    "BOVINO, LINGUA",
                    "BOVINO, LINGUA SALMISTRATA",
                    "BOVINO, MIDOLLO OSSEO",
                    "BOVINO, MILZA",
                    "BOVINO, POLMONE",
                    "BOVINO, RENE",
                    "BOVINO, SANGUE",
                    "BOVINO, TRIPPA",
                    "BRA",
                    "BRANDY",
                    "BRESAOLA",
                    "BRIE",
                    "BRIOCHES",
                    "BRIOCHES CON CREMA",
                    "BRIOCHES CON MARMELLATA",
                    "BROCCOLETTI DI RAPE [BRASSICA RAPA, CV ESCULENTA]",
                    "BROCCOLO A TESTA [BRASSICA OLERACEA, CV BOTRYTIS CAPUT]",
                    "BRODO DI CARNE E VERDURA",
                    "BRODO DI CARNE VARIA",
                    "BRODO DI DADO",
                    "BRODO DI GALLINA",
                    "BRODO VEGETALE",
                    "BUCCIA D'ARANCIA CANDITA",
                    "BUDINO AL CIOCCOLATO",
                    "BUDINO ALLA VANIGLIA",
                    "BURRATA",
                    "BURRINI",
                    "BURRO",
                    "BURRO DI ARACHIDI",
                    "CACAO AMARO, IN POLVERE",
                    "CACAO DOLCE, IN POLVERE, SOLUBILE",
                    "CACIOCAVALLO",
                    "CACIOCAVALLO AFFUMICATO",
                    "CACIOTTA AFFUMICATA",
                    "CACIOTTA ROMANA DI PECORA",
                    "CACIOTTA TOSCANA",
                    "CACIOTTINA FRESCA",
                    "CAFFE' ALL'AMERICANA, in tazza",
                    "CAFFE' BAR, in tazza",
                    "CAFFE' CRUDO, in grani",
                    "CAFFE' DECAFFEINATO, in tazza",
                    "CAFFE' DECAFFEINATO, TOSTATO, MACINATO",
                    "CAFFE' MOKA, in tazza",
                    "CAFFE' SOLUBILE, DECAFFEINATO, in polvere",
                    "CAFFE' SOLUBILE, DECAFFEINATO, in tazza",
                    "CAFFE' SOLUBILE, in polvere",
                    "CAFFE' SOLUBILE, in tazza",
                    "CAFFE' TOSTATO, MACINATO",
                    "CALAMARO [LOLIGO VULGARIS]",
                    "CALAMARO SURGELATO",
                    "CAMEMBERT",
                    "CANDITI",
                    "CANNELLA [CINNAMOMUM VERUM e AROMATICUM]",
                    "CANNOLI ALLA CREMA",
                    "CAPOCOLLO",
                    "CAPPERI SOTT'ACETO",
                    "CAPRETTO [CAPRA HIREUS]",
                    "CAPRIOLO [CERVUS spp], COSCIA",
                    "CAPRIOLO [CERVUS spp], SCHIENA",
                    "CARAMELLE ALLA FRUTTA",
                    "CARAMELLE ALLA MENTA",
                    "CARAMELLE DURE",
                    "CARAMELLE MORBIDE, MOU",
                    "CARCIOFI [CYNARA SCOLYMUS]",
                    "CARCIOFI SURGELATI",
                    "CARCIOFINI SOTT'ACETO",
                    "CARCIOFINI SOTT'OLIO",
                    "CARDI [CYNARA CARDUNCULUS]",
                    "CAROTE [DAUCUS CAROTA]",
                    "CARPA [CYPRINUS CARPIO]",
                    "CASTAGNE [CASTANEA SATIVA]",
                    "CASTAGNE, secche",
                    "CASTRATO [OVIS AGNUS], CARNE SEMIGRASSA",
                    "CASTRATO, CARNE GRASSA",
                    "CASTRATO, CARNE MAGRA",
                    "CAVALLO [EQUUS CABALUS]",
                    "CAVALLO, CUORE",
                    "CAVALLO, FEGATO",
                    "CAVIALE",
                    "CAVOLFIORE [BRASSICA OLERACEA, CV BOTRYTIS CAULIFLAURA]",
                    "CAVOLI DI BRUXELLES [BRASSICA OLERACEA, CV GEMMIFERA]",
                    "CAVOLO BROCCOLO VERDE RAMOSO [BRASSICA OLERACEA CV BOTRITYS CIMOSA]",
                    "CAVOLO CAPPUCCIO ROSSO [BRASSICA OLERACEA, CV CAPITATA RUBRA]",
                    "CAVOLO CAPPUCCIO VERDE [BRASSICA OLERACEA, CV CAPITATA ALBA]",
                    "CECI [CICER ARIETINUM], secchi",
                    "CECI IN SCATOLA",
                    "CEDRO CANDITO",
                    "CEFALO MUGGINE [MUGIL CEPHALUS]",
                    "CEREALI AGGREGATI",
                    "CERNIA [EPINEPHELUS GUAZA]",
                    "CERNIA DI FONDO [POLYPRION CERNIUM]",
                    "CERNIA SURGELATA",
                    "CERTOSINO",
                    "CETRIOLI [CUCUMIS SATIVUS]",
                    "CETRIOLI IN SALAMOIA",
                    "CETRIOLINI SOTT'ACETO",
                    "CHAMPAGNE",
                    "CHEDDAR",
                    "CHERRY BRANDY",
                    "CICCIOLI",
                    "CICORIA [CICHORIUM INTYBUS]",
                    "CICORIA CATALOGNA [CHICORIUM INTYBUS, CV CATALOGNA]",
                    "CICORIA DA TAGLIO [CHICORIUM INTYBUS, CV BARBA DI FRATE]",
                    "CICORIA WITLOOF [CHICORIUM INTYBUS, CV. WITLOOF]",
                    "CILIEGE [PRUNUS AVIUM]",
                    "CIOCCOLATO AL LATTE",
                    "CIOCCOLATO BIANCO",
                    "CIOCCOLATO CON NOCCIOLE",
                    "CIOCCOLATO FONDENTE",
                    "CIOCCOLATO GIANDUIA",
                    "CIPOLLE [ALLIUM CEPA]",
                    "CIPOLLE, secche",
                    "CIPOLLINE [ALLIUM CEPA, CV PRAECOX]",
                    "CIPOLLINE SOTT'ACETO",
                    "COCA COLA",
                    "COCOMERO [CITRULLUS VULGARIS]",
                    "COGNAC",
                    "CONFETTI",
                    "CONIGLIO [ORYCTOLAGUS CUNICULUS], CARNE SEMIGRASSA",
                    "CONIGLIO, CARNE GRASSA",
                    "CONIGLIO, CARNE MAGRA",
                    "CONIGLIO, FRATTAGLIE",
                    "CONO PER GELATO",
                    "COPPA",
                    "COPPA PARMA",
                    "CORNED BEEF IN SCATOLA",
                    "COTECHINO",
                    "COTECHINO, cotto",
                    "COZZA O MITILO [MYTILUS EDULIS]",
                    "CRACKERS AL FORMAGGIO",
                    "CRACKERS INTEGRALI",
                    "CRACKERS NON SALATI",
                    "CRACKERS SALATI",
                    "CRACKERS SENZA GRASSI",
                    "CRACOTTE",
                    "CRAUTI",
                    "CREMA DI CACAO E NOCCIOLE",
                    "CREMA PER PASTICCERIA",
                    "CREME CARAMEL",
                    "CRESCIONE [NASTURTIUM OFFICINALIS]",
                    "CROSTATA CON MARMELLATA",
                    "CRUSCA DI GRANO",
                    "CUMINO [CUMINUM CYMINUM], SEMI",
                    "DADI PER BRODO",
                    "DADI PER BRODO VEGETALE",
                    "DAIKON [RAPHUS SATIVUS]",
                    "DATTERI [PHOENIX DACTYLIFERA], freschi",
                    "DATTERI, secchi",
                    "DENTICE [DENTEX DENTEX]",
                    "DENTICE SURGELATO",
                    "DOLCE VERDE",
                    "DOLCIFICANTE A BASE DI SACCARINA",
                    "DOLCIFICANTE ASPARTAME",
                    "DOLCIFICANTE FRUTTOSIO",
                    "DOLCIFICANTE SACCARINA",
                    "EDAM STAGIONATO",
                    "EDAM, FRESCO",
                    "EMMENTHAL",
                    "ERBA CIPOLLINA [ALLIUM SCHOENOPRASUM], fresca",
                    "ESTRATTO DI CARNE BOVINA",
                    "FAGIANO [PHASIANUS COLCHICUS]",
                    "FAGIOLI [PHASEOLUS VULGARIS]",
                    "FAGIOLI ADUKI [VIGNA ANGULARIS], secchi",
                    "FAGIOLI IN SCATOLA",
                    "FAGIOLI MUNG [PHASEOLUS AUREUS], secchi",
                    "FAGIOLI, secchi",
                    "FAGIOLINI [PHASEOLUS VULGARIS]",
                    "FAGIOLINI IN SCATOLA",
                    "FARAONA [NUMIDA MELEAGRIS]",
                    "FARAONA, COSCIA",
                    "FARAONA, PETTO",
                    "FARINA DI AVENA",
                    "FARINA DI CASTAGNE",
                    "FARINA DI CECI",
                    "FARINA DI COCCO",
                    "FARINA DI FRUMENTO, INTEGRALE",
                    "FARINA DI FRUMENTO, TIPO ",
                    "FARINA DI FRUMENTO, TIPO ",
                    "FARINA DI GRANO DURO",
                    "FARINA DI GRANO SARACENO",
                    "FARINA DI MAIS",
                    "FARINA DI ORZO",
                    "FARINA DI RISO",
                    "FARINA DI SEGALE, integrale",
                    "FARINA DI SEGALE, semi0integrale",
                    "FARINA DI SOIA, a basso contenuto lipidico",
                    "FARINA DI SOIA, intera",
                    "FARINA LATTEA",
                    "FAVE [VICIA FABA]",
                    "FAVE SECCHE",
                    "FETA",
                    "FETTE BISCOTTATE",
                    "FETTE BISCOTTATE, DOLCI",
                    "FETTE BISCOTTATE, INTEGRALI",
                    "FETTE BISCOTTATE, VITAMINIZZATE",
                    "FETTE DI SEGALE INTEGRALI",
                    "FICHI [FICUS CARICA]",
                    "FICHI D'INDIA [OPUNTIA FICUS INDICA]",
                    "FICHI SECCATI AL FORNO E MANDORLATI",
                    "FICHI SECCATI AL SOLE",
                    "FICHI SECCHI",
                    "FINOCCHIO [PHOENICULUM VULGARE]",
                    "FINOCCHIO [PHOENICULUM VULGARE], SEMI",
                    "FIOCCHI DI AVENA",
                    "FIOCCHI DI CRUSCA DI GRANO",
                    "FIOCCHI DI LATTE MAGRO",
                    "FIOCCHI DI MAIS (CORNFLAKES)",
                    "FIOCCHI DI RISO",
                    "FIOCCHI D'ORZO",
                    "FIOR DI LATTE",
                    "FIORI DI ZUCCA [CUCURBITA PEPO]",
                    "FOCACCIA",
                    "FOGLIE DI RAPA [BRASSICA RAPA]",
                    "FONTINA",
                    "FORMAGGINO",
                    "FORMAGGINO, a basso tenore di lipidi",
                    "FORMAGGIO AL GORGONZOLA E AL MASCARPONE",
                    "FORMAGGIO SPALMABILE (tipo Philadelphia)",
                    "FRAGOLE [FRAGARIA VESCA]",
                    "FRUMENTO DURO [TRITICUM DURUM]",
                    "FRUMENTO TENERO [TRITICUM AESTIVUM]",
                    "FUNGHI CHIODINI [ARMILLARIA MELLEA]",
                    "FUNGHI GALLINACCI [CANTHARELLUS CIBARIUS FRIES]",
                    "FUNGHI GALLINACCI, secchi",
                    "FUNGHI IN SCATOLA",
                    "FUNGHI OVULI [AMANITA CAESARIA, OVULO EDULE]",
                    "FUNGHI PORCINELLI [LECINUM SCABRUM]",
                    "FUNGHI PORCINI [BOLETUS EDULIS]",
                    "FUNGHI PRATAIOLI, COLTIVATI [AGARICUS CAMPESTRIS]",
                    "FUNGHI SECCHI",
                    "FUNGHI SHIITAKE [LENTINUS EDODES], secchi",
                    "FUNGHI SOTT'OLIO",
                    "FUNGHI SPUGNOLI [MORCHELLA ESCULENTA]",
                    "GALLINA [GALLUS GALLUS]",
                    "GAMBERETTI DI LAGO [ASTACUS spp]",
                    "GAMBERETTI SURGELATI",
                    "GAMBERO [CRANGON VULGARIS]",
                    "GELATINA ALIMENTARE, secca",
                    "GELATO AL CIOCCOLATO",
                    "GELATO ALLA FRUTTA",
                    "GELATO FIOR DI LATTE",
                    "GERME DI GRANO",
                    "GERMOGLI DI ERBA MEDICA [MEDICAGO SATIVA]",
                    "GHIACCIOLO ALL'ARANCIO",
                    "GIARDINIERA SOTT'ACETO",
                    "GIARDINIERA SOTT'OLIO",
                    "GIRASOLE, SEMI",
                    "GOMME DA MASTICARE",
                    "GORGONZOLA",
                    "GORGONZOLA CON LE NOCI",
                    "GOUDA FRESCO",
                    "GOUDA STAGIONATO",
                    "GRANA",
                    "GRANCHIO [CALLINECTES SAPIDUS]",
                    "GRANCHIO, POLPA IN SCATOLA",
                    "GRANITA DI LIMONE",
                    "GRANITO DI TENERO",
                    "GRAPPA",
                    "GRISSINI",
                    "GRISSINI INTEGRALI",
                    "GROVIERA",
                    "HALIBUT [HIPPOGLOSSUS HIPPOGLOSSUS]",
                    "INDIVIA [CHICORIUM ENDIVIA]",
                    "INSALATA DI RISO",
                    "IRISH MOSS [CHONDRUS CRISPUS], fresca",
                    "ITALICO (tipo Bel Paese)",
                    "KAKI O LOTI [DIOSPYROS KAKI]",
                    "KIWI [ACTINIDIA DELICIOSA]",
                    "KOMBU [LAMINARIA spp], secca",
                    "LAMPONI [RUBUS IDAEUS]",
                    "LARDO",
                    "LATTE DI BUFALA",
                    "LATTE DI CAPRA",
                    "LATTE DI MANDORLE",
                    "LATTE DI PECORA",
                    "LATTE DI SOIA",
                    "LATTE DI VACCA, CONDENSATO, CON ZUCCHERO",
                    "LATTE DI VACCA, INTERO",
                    "LATTE DI VACCA, INTERO UHT",
                    "LATTE DI VACCA, INTERO VITAMINIZZATO",
                    "LATTE DI VACCA, INTERO, IN POLVERE",
                    "LATTE DI VACCA, PARZIALMENTE SCREMATO",
                    "LATTE DI VACCA, PARZIALMENTE SCREMATO UHT",
                    "LATTE DI VACCA, PARZIALMENTE SCREMATO VITAMINIZZATO",
                    "LATTE DI VACCA, PARZIALMENTE SCREMATO, IN POLVERE",
                    "LATTE DI VACCA, SCREMATO",
                    "LATTE DI VACCA, SCREMATO IN POLVERE",
                    "LATTE DI VACCA, SCREMATO UHT",
                    "LATTE EVAPORATO",
                    "LATTERIA",
                    "LATTERINI [ATHERINA BOYERI]",
                    "LATTUGA [LACTUCA SATIVA]",
                    "LATTUGA A CAPPUCCIO [LACTUCA SATIVA, CV CAPITATA]",
                    "LATTUGA DA TAGLIO [LACTUCA SATIVA, CV ACEPHALA]",
                    "LENTICCHIE [LENS ESCULENTA], secche",
                    "LENTICCHIE IN SCATOLA",
                    "LEPRE [LEPUS EUROPAENUS], COSCIO",
                    "LIEVITO DI BIRRA, COMPRESSO",
                    "LIMETTE [CITRUS AURANTIFOLIA]",
                    "LIMONE [CITRUS LIMONUM]",
                    "LIMONE, SCORZA",
                    "LINO, SEMI",
                    "LIQUIRIZIA DOLCE",
                    "LIQUORI DA DESSERT",
                    "LUCCIO [ESOX LUCIUS]",
                    "LUMACA [HELIX POMATIA]",
                    "LUMACHE DI MARE [BUCCINIDAE spp]",
                    "LUPINI [LUPINUS ALBUS] DEAMARIZZATI",
                    "MACEDONIA DI FRUTTA IN SCATOLA",
                    "MAGGIORANA [MAJORANA HORTENSIS], secca",
                    "MAIONESE",
                    "MAIS [ZEA MAYS]",
                    "MAIS DOLCE IN SCATOLA",
                    "MAIS DOLCE, crudo",
                    "MANDARANCI e CLEMENTINE",
                    "MANDARINI [CITRUS NOBILIS]",
                    "MANDORLE DOLCI [PRUNUS COMMUNIS]",
                    "MANGO [MANGIFERA INDICA]",
                    "MARGARINA",
                    "MARGARINA VEGETALE",
                    "MARMELLATA (ALBIC.,FICHI,MELE COT.,PESCHE, PRUGNE]",
                    "MARMELLATA (AMARENE,CILIEGE,UVA,MARASCHE)",
                    "MARMELLATA (NORMALI E TIPO FRUTTA VIVA)",
                    "MARMELLATA A RIDOTTO TENORE DI ZUCCHERO",
                    "MARMELLATA DI ALBICOCCHE",
                    "MARMELLATA DI ARANCE",
                    "MARMELLATA DI PRUGNE",
                    "MARSALA ALL'UOVO",
                    "MARSALA TIPICO",
                    "MASCARPONE",
                    "MELA [PYRUS MALUS]",
                    "MELA COTOGNA [PYRUS CYDONIA]",
                    "MELA, polpa secca",
                    "MELAGRANE [PUNICA GRANATUM]",
                    "MELANZANE [SOLANUM MELONGEA]",
                    "MELANZANE SOTT'OLIO",
                    "MELONE D'ESTATE [CUCUMIS MELO]",
                    "MELONE D'INVERNO [CUCUMIS MELO, CV INDORUS]",
                    "MELU' O PESCE MOLO [GADUS POTASSOU]",
                    "MENTA [MENTHA SPICATA], fresca",
                    "MENTA, secca",
                    "MERENDINE AL CIOCCOLATO",
                    "MERENDINE CON MARMELLATA",
                    "MERENDINE FARCITE",
                    "MERENDINE TIPO PAN DI SPAGNA",
                    "MERINGA",
                    "MERLUZZO [MERLUCCIUS MERLUCCIUS]",
                    "MERLUZZO SURGELATO",
                    "MIELE",
                    "MIRTILLO NERO [VACCINIUM MYRTILLUS]",
                    "MISO",
                    "MONTASIO",
                    "MORA DI GELSO [MORUS NIGRA]",
                    "MORA DI ROVO [RUBUS FRUTICOSUS]",
                    "MORTADELLA DI SUINO",
                    "MORTADELLA DI SUINO E BOVINO",
                    "MOZZARELLA",
                    "MOZZARELLA DI BUFALA",
                    "MUESLI",
                    "NATTO",
                    "NESPOLE [ERIOBOTRYA JAPONICA]",
                    "NOCCIOLE [CORYLUS AVELLANA]",
                    "NOCE DI COCCO [COCOS NUCIFERA]",
                    "NOCE MOSCATA [MYRISTICA FRAGRANS]",
                    "NOCI [JUGLANS REGIA], fresche",
                    "NOCI, secche",
                    "NORI [PORPHYRA LACINIATA], secca",
                    "OCA [ANSER ANSER]",
                    "OLIO DI COCCO",
                    "OLIO DI COLZA",
                    "OLIO DI GERME DI GRANO",
                    "OLIO DI MAIS VITAMINIZZATO",
                    "OLIO DI OLIVA",
                    "OLIO DI OLIVA EXTRAVERGINE",
                    "OLIO DI OLIVA VITAMINIZZATO",
                    "OLIO DI PALMA",
                    "OLIO DI SEMI DI ARACHIDI",
                    "OLIO DI SEMI DI GIRASOLE",
                    "OLIO DI SEMI DI MAIS",
                    "OLIO DI SEMI VARI",
                    "OLIO DI SESAMO",
                    "OLIO DI SOIA",
                    "OLIO DI VINACCIOLO",
                    "OLIVE DA TAVOLA, CONSERVATE",
                    "OLIVE NERE [OLEA EUROPEA SATIVA]",
                    "OLIVE VERDI [OLEA EUROPEA]",
                    "OMBRINA [OMBRINA CIRROSA] SURGELATA",
                    "ORATA [SPARUS AURATUS], SURGELATA",
                    "ORIGANO [ORIGANUM VULGARE], fresco",
                    "ORIGANO, secco macinato",
                    "ORTICA [URTICA DIOICA]",
                    "ORZO [HORDEUM VULGARE], PERLATO",
                    "ORZO SOLUBILE O CAFFE' D'ORZO, in polvere",
                    "ORZO SOLUBILE O CAFFE' D'ORZO, in tazza",
                    "OSTRICA [OSTREA EDULIS]",
                    "OVINO, CUORE",
                    "OVINO, FEGATO",
                    "PALOMBO [MUSTELUS MUSTELUS]",
                    "PAN DI SPAGNA",
                    "PANCARRE' AMERICANO COMUNE",
                    "PANCETTA AFFUMICATA O BACON",
                    "PANCETTA COPPATA",
                    "PANCETTA DI MAIALE",
                    "PANCETTA MAGRETTA",
                    "PANCETTA TESA",
                    "PANE AL LATTE",
                    "PANE ALLE OLIVE",
                    "PANE COMUNE, pezzatura da g",
                    "PANE CONDITO",
                    "PANE DI GRANO DURO",
                    "PANE DI GRANO E SEGALE",
                    "PANE DI SEGALE",
                    "PANE DI SEGALE BISCOTTATO",
                    "PANE DI SOIA",
                    "PANE GRATTUGIATO",
                    "PANE INTEGRALE",
                    "PANE TOSTATO",
                    "PANE, TIPO , pezzatura > g",
                    "PANE, TIPO , pezzatura da g",
                    "PANE, TIPO , pezzatura da g",
                    "PANETTONE",
                    "PANINI ALL'OLIO",
                    "PANNA, % di lipidi",
                    "PANNA, % di lipidi",
                    "PANNA, % di lipidi (da cucina)",
                    "PANNA, a basso contenuto di colesterolo",
                    "PAPAYA [CARICA PAPAYA]",
                    "PAPRIKA [CAPSICUM ANNUUM], in polvere",
                    "PARMIGIANO",
                    "PASTA ALL'UOVO, fresca",
                    "PASTA ALL'UOVO, secca",
                    "PASTA DI MANDORLE",
                    "PASTA DI OLIVE",
                    "PASTA DI SEMOLA",
                    "PASTA DI SEMOLA INTEGRALE",
                    "PASTA FROLLA",
                    "PASTA SFOGLIA",
                    "PASTI DIETETICI SOSTITUTIVI",
                    "PASTICCINI AL COCCO",
                    "PASTORELLA",
                    "PATATE [SOLANUM TUBEROSUM]",
                    "PATATE DOLCI [IPOMAEA BATATAS]",
                    "PATATE NOVELLE [SOLANUM TUBEROSUM]",
                    "PATATE, FECOLA",
                    "PATATE, POLVERE ISTANTANEA",
                    "PATATINE IN SACCHETTO",
                    "PECORA [OVIS ARIES]",
                    "PECORINO",
                    "PECORINO DA GRATTUGIARE",
                    "PECORINO ROMANO",
                    "PECORINO, FRESCO",
                    "PEPE NERO [PIPER NIGRUM]",
                    "PEPERONCINI PICCANTI [CAPSICUM ANNUUM]",
                    "PEPERONI DOLCI [CAPSICUM ANNUUM]",
                    "PEPERONI GIALLI [CAPSICUM ANNUUM, CV GROSSUM]",
                    "PEPERONI SOTT'ACETO",
                    "PERA [PYRUS COMMUNIS]",
                    "PESCA [PRUNUS PERSICA]",
                    "PESCA SCIROPPATA",
                    "PESCE PERSICO [PERCA FLUVIATILIS]",
                    "PESCE SPADA [XIPHIAS GLADIUS]",
                    "PICCIONE ADULTO [COLUMBA LIVIA]",
                    "PICCIONE GIOVANE [COLUMBA LIVIA]",
                    "PINOLI [PINUS PINEA]",
                    "PISELLI [PISUM SATIVUM], freschi",
                    "PISELLI IN SCATOLA",
                    "PISELLI IN SCATOLA SGOCCIOLATI",
                    "PISELLI SURGELATI",
                    "PISELLI, secchi",
                    "PISTACCHI [PISTACIA VERA], freschi",
                    "PISTACCHI, secchi",
                    "PISTACCHI, tostati e salati",
                    "PIZZA CON POMODORO",
                    "PIZZA CON POMODORO E MOZZARELLA",
                    "POLENTA",
                    "POLLO [GALLUS GALLUS], INTERO",
                    "POLLO, ALI",
                    "POLLO, COSCIA",
                    "POLLO, FEGATINI",
                    "POLLO, PETTO",
                    "POLLO, REGAGLIE",
                    "POLPO [OCTOPUS VULGARIS]",
                    "POLPO SURGELATO",
                    "POMODORI DA INSALATA [SOLANUM LYCOPERSICUM]",
                    "POMODORI MATURI [SOLANUM LYCOPERSICUM]",
                    "POMODORI SECCHI",
                    "POMODORI SOTT'OLIO",
                    "POMODORI, PELATI, IN SCATOLA CON LIQUIDO",
                    "POMODORO, CONCENTRATO (sostanza secca 8%)",
                    "POMODORO, CONCENTRATO (sostanza secca 25%)",
                    "POMODORO, CONSERVA (sostanza secca 30%)",
                    "POMPELMO [CITRUS PARADISI]",
                    "POMPELMO ROSA [CITRUS PARADISI]",
                    "POP CORN",
                    "PORRI [ALLIUM PORRUM]",
                    "PORTO",
                    "PREZZEMOLO [PETROSELINUM SATIVUM], fresco",
                    "PREZZEMOLO, secco",
                    "PROSCIUTTO COTTO",
                    "PROSCIUTTO COTTO, AFFUMICATO",
                    "PROSCIUTTO COTTO, MAGRO",
                    "PROSCIUTTO CRUDO",
                    "PROSCIUTTO CRUDO, AFFUMICATO",
                    "PROSCIUTTO CRUDO, MAGRO",
                    "PROVOLA AFFUMICATA",
                    "PROVOLONCINO DOLCE",
                    "PROVOLONE",
                    "PROVOLONE PICCANTE",
                    "PRUGNE [PRUNUS DOMESTICA]",
                    "PRUGNE REGINA CLAUDIA [PRUNUS DOMESTICA, CV ITALICA]",
                    "PRUGNE, secche",
                    "QUAGLIA [COTURNIX COTURNIX]",
                    "RADICCHIO ROSSO [CICHORIUM INTYBUS]",
                    "RADICCHIO VERDE [CICHORIUM INTYBUS]",
                    "RANA [RANA ESCULENTA]",
                    "RANA PESCATRICE [LOPHIUS PISCATORIUS]",
                    "RAPE [BRASSICA RAPA]",
                    "RAVANELLI [RAPHANUS SATIVUS]",
                    "RAZZA [RAJA ASTERIAS]",
                    "RHUM",
                    "RIBES NERO [RIBES NIGRUM]",
                    "RIBES ROSSO [RIBES RUBRUM]",
                    "RICOTTA DI PECORA",
                    "RICOTTA DI VACCA",
                    "RICOTTA DI VACCA E PECORA",
                    "RICOTTA INTERA, TIPO TEDESCO",
                    "RICOTTA MAGRA TIPO TEDESCO",
                    "RISO [ORYZA SATIVA], BRILLATO",
                    "RISO SOFFIATO",
                    "RISO, SBRAMATO (INTEGRALE)",
                    "RISO, TIPO PARBOILED",
                    "ROBIOLA",
                    "ROCHEFORT",
                    "ROMBO [RHOMBUS MAXIMUM]",
                    "ROSMARINO [ROSMARINUS OFFICINALIS], fresco",
                    "ROSMARINO, secco",
                    "RUCOLA [ERUCA SATIVA]",
                    "SALAME CACCIATORE",
                    "SALAME DA CUOCERE",
                    "SALAME DI SUINO",
                    "SALAME DI SUINO E BOVINO",
                    "SALAME FABRIANO",
                    "SALAME FELINO",
                    "SALAME MILANO",
                    "SALAME NAPOLI",
                    "SALAME NOSTRANO",
                    "SALAME UNGHERESE",
                    "SALATINI",
                    "SALE da cucina",
                    "SALMONE [SALMO SALAR]",
                    "SALMONE AFFUMICATO",
                    "SALMONE IN SALAMOIA",
                    "SALSICCIA DI FEGATO",
                    "SALSICCIA DI SUINO E BOVINO, fresca",
                    "SALSICCIA DI SUINO, fresca",
                    "SALSICCIA DI SUINO, secca",
                    "SALVIA [SALVIA OFFICINALIS], fresca",
                    "SALVIA, secca macinata",
                    "SARAGO [DIPLODUS SARGUS]",
                    "SARDA [SARDINA PILCHARDUS]",
                    "SARDINE SALATE",
                    "SARDINE SOTT'OLIO",
                    "SCALOGNO [ALLIUM ASCALONIUM]",
                    "SCAMORZA",
                    "SCAMORZA AFFUMICATA",
                    "SCAROLA [LACTUCA SCAROLA]",
                    "SCIROPPO DI MALTO",
                    "SCIROPPO PER BIBITE",
                    "SCORZONERA [TRAGOPOGON PORRIFOLIUS]",
                    "SEDANO [APIUM GRAVEOLENS]",
                    "SEDANO RAPA [APIUM GRAVEOLENS, CV RAPACEUM]",
                    "SEGO DI BUE",
                    "SEMOLA",
                    "SEPPIA [SEPIA OFFICINALIS]",
                    "SEPPIA SURGELATA",
                    "SGOMBRO O MACCARELLO [SCOMBER SCOMBRUS]",
                    "SGOMBRO O MACCARELLO IN SALAMOIA",
                    "SGOMBRO, FILETTI SOTT'OLIO",
                    "SHOYU, salsa di soia e grano",
                    "SODA DOLCE",
                    "SOFFICINI AL FORMAGGIO SURGELATI",
                    "SOGLIOLA [SOLEA SOLEA]",
                    "SOGLIOLA SURGELATA",
                    "SOIA [GLYCINE MAX], SEMI",
                    "SOIA, BISTECCA",
                    "SOIA, GERMOGLI",
                    "SOTTILETTE",
                    "SPECK",
                    "SPIGOLA [MORONE LABRAX]",
                    "SPINACI [SPINACIA OLERACEA]",
                    "SPINACI IN SCATOLA",
                    "SPREMUTA DI ARANCIA",
                    "SPREMUTA DI POMPELMO",
                    "SPUMANTI AROMATICI",
                    "SPUMANTI DEMI0SEC",
                    "SPUMANTI SECCHI",
                    "STARNA [PERDIX PERDIX], COSCIO",
                    "STOCCAFISSO [GADUS POUTASSOU], ammollato",
                    "STOCCAFISSO, secco",
                    "STRACCHINO",
                    "STRUTTO O SUGNA",
                    "SUCCO DI ALBICOCCA, CONSERVATO",
                    "SUCCO DI ANANAS, CONSERVATO",
                    "SUCCO DI ARANCIA E POMPELMO non zuccherato",
                    "SUCCO DI ARANCIA, CONCENTRATO",
                    "SUCCO DI ARANCIA, CONSERVATO, non zuccherato",
                    "SUCCO DI BARBABIETOLA, FRESCO",
                    "SUCCO DI CAROTE, CONSERVATO",
                    "SUCCO DI FRUTTA, CONSERVATO",
                    "SUCCO DI LIMONE, CONSERVATO",
                    "SUCCO DI LIMONE, FRESCO",
                    "SUCCO DI MANDARINO, CONSERVATO, non zuccherat",
                    "SUCCO DI MANDARINO, FRESCO",
                    "SUCCO DI MELA, CONSERVATO, non zuccherato",
                    "SUCCO DI MELAGRANA, FRESCO",
                    "SUCCO DI PERA, CONSERVATO",
                    "SUCCO DI PESCA, CONSERVATO",
                    "SUCCO DI POMODORO, CONSERVATO",
                    "SUCCO DI POMPELMO, CONSERVATO, non zuccherato",
                    "SUCCO DI POMPELMO, CONSERVATO, zuccherato",
                    "SUCCO DI SPINACI",
                    "SUCCO DI UVA, CONSERVATO, non zuccherato",
                    "SUCCO TROPICALE, CONSERVATO",
                    "SUINO [SUS SCROFA], CARNE SEMIGRASSA",
                    "SUINO, BISTECCA",
                    "SUINO, CARNE MAGRA",
                    "SUINO, COSCIO",
                    "SUINO, CUORE",
                    "SUINO, FEGATO",
                    "SUINO, SANGUE",
                    "SURIMI",
                    "TACCHINA [MELEAGRIS GALLOPAVO], PETTO",
                    "TACCHINA, ALA",
                    "TACCHINA, COSCIA",
                    "TACCHINO [MELEAGRIS GALLOPAVO], INTERO",
                    "TACCHINO, ALA",
                    "TACCHINO, COSCIA",
                    "TACCHINO, PETTO",
                    "TALEGGIO",
                    "TAMARI, salsa di soia",
                    "TAPIOCA [MANIHOT UTILISSIMA]",
                    "TARTUFO NERO [TUBER MELANOSPORUM]",
                    "TE' DETEINATO, in foglie",
                    "TE' DETEINATO, in tazza",
                    "TE', in foglie",
                    "TE', in tazza",
                    "TEMPEH",
                    "TIMO [THYMUS VULGARIS], fresco",
                    "TIMO, secco macinato",
                    "TINCA [TINCA TINCA]",
                    "TIRAMISU'",
                    "TISANA IN TAZZA",
                    "TOFU",
                    "TONNO [THUNNUS THYNNUS]",
                    "TONNO IN SALAMOIA, SGOCCIOLATO",
                    "TONNO SOTT'OLIO, SGOCCIOLATO",
                    "TORDO [TURDUS ERYCETORUM]",
                    "TORRONE CON MANDORLE",
                    "TORTA AL CIOCCOLATO",
                    "TORTA MARGHERITA",
                    "TORTELLINI, freschi",
                    "TORTELLINI, secchi",
                    "TRIGLIA [MULLUS SURMULETUS]",
                    "TROTA [SALMO TRUTTA]",
                    "UOVO DI ANATRA",
                    "UOVO DI GALLINA, ALBUME",
                    "UOVO DI GALLINA, INTERO",
                    "UOVO DI GALLINA, INTERO, IN POLVERE",
                    "UOVO DI GALLINA, TUORLO",
                    "UOVO DI OCA",
                    "UOVO DI TACCHINA",
                    "UVA [VITIS VINIFERA]",
                    "UVA SULTANINA/UVETTA, UVA SECCA",
                    "VALERIANA [VALERIANELLA OLITORIA]",
                    "VANIGLIA, estratto alcolico",
                    "VENTAGLIO O PETTINE [PECTEN JACOBEAUS]",
                    "VERDURA E LEGUMI, SURGELATI",
                    "VERMOUTH DOLCE",
                    "VERMOUTH SECCO",
                    "VINO BIANCO",
                    "VINO ROSATO",
                    "VINO ROSSO",
                    "VITELLO [BOS TAURUS], CARNE MAGRA",
                    "VITELLO, CARNE SEMIGRASSA",
                    "VITELLO, CORATELLA",
                    "VITELLONE [BOS TAURUS], CARNE SEMIGRASSA",
                    "VITELLONE, CARNE GRASSA",
                    "VITELLONE, CARNE MAGRA",
                    "VITELLONE, tagli di carne grassa",
                    "VITELLONE, tagli di carne magra",
                    "VITELLONE, tagli di carne semigrassa",
                    "VODKA",
                    "VONGOLA [AMIGDALA DECUSSATA]",
                    "VONGOLE IN SCATOLA, AL NATURALE",
                    "WAKAME [UNDARIA spp], secca",
                    "WHISKY",
                    "WURSTEL",
                    "WURSTEL DI POLLO",
                    "WURSTEL DI TACCHIN",
                    "YOGURT DI LATTE INTERO",
                    "YOGURT DI LATTE INTERO AI CEREALI E MALTO",
                    "YOGURT DI LATTE INTERO ALLA FRUTTA",
                    "YOGURT DI LATTE MAGRO ALLA FRUTTA",
                    "YOGURT DI LATTE PARZIALMENTE SCREMATO",
                    "YOGURT DI LATTE SCREMATO",
                    "ZAFFERANO [CROCUS SATIVUS]",
                    "ZAMPONE",
                    "ZUCCA GIALLA [CUCURBITA MAXIMA]",
                    "ZUCCHERO (Saccarosio)",
                    "ZUCCHERO DI CANNA, GREZZO",
                    "ZUCCHINE [CUCURBITA PEPO]"
                )
                li.forEach {
                    dao.insertIngrediente(Ingrediente(it, false))
                }
                dao.insertRicettaPreview(RicettePreview("pietanza 1",false))
                dao.insertRicettaCompleta(RicettaCompleta("pietanza 1","la si cucina quando si è a casa da soli"))
                dao.insertIngredienteRicetta(ingrRic = IngredienteRIcetta("pietanza 1","UOVO DI OCA",2))
                dao.insertIngredienteRicetta(ingrRic = IngredienteRIcetta("pietanza 1","VINO ROSATO",200))
                dao.insertRicetteCategoria(rc = RicettaCategorie("pietanza 1","secondo"))
                dao.insertRicetteCategoria(rc = RicettaCategorie("pietanza 1","vegano"))

                dao.insertRicettaPreview(RicettePreview("pietanza 2",false))
                dao.insertRicettaCompleta(RicettaCompleta("pietanza 2","la si cucina quando si è ad una festa"))
                dao.insertIngredienteRicetta(ingrRic = IngredienteRIcetta("pietanza 2","WHISKY",200))
                dao.insertIngredienteRicetta(ingrRic = IngredienteRIcetta("pietanza 2","VODKA",200))
                dao.insertRicetteCategoria(rc = RicettaCategorie("pietanza 2","antipasto"))
                dao.insertRicetteCategoria(rc = RicettaCategorie("pietanza 2","vegano"))
            }
        }
    }
}